services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
    volumes:
      - ./db/pgdata:/var/lib/postgresql/data
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
    ports:
      - 27017:27017
    volumes:
      - ./db/mongodb_data:/var/lib/mongodb/data
  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    ports:
      - 5672:5672 #main port
      - 15672:15672 #management port
volumes:
  pgdata:
  mongodb_data:
