services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
    volumes:
      - ./db/pgdata:/var/lib/postgresql/data
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
    ports:
      - 27017:27017
    volumes:
      - ./db/mongodb_data:/var/lib/mongodb/data
  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    ports:
      - 5672:5672 #main port
      - 15672:15672 #management port
  auction-svc:
    image: 1811063460/auction-svc:lastest
    build:
      context: .
      dockerfile: src/AuctionService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__DefaultConnection=Server=postgres;Port=5432;User Id=postgres;Password=123456;Database=auction;Pooling=true;Minimum Pool Size=0;Maximum Pool Size=100
      - IdentityServiceUrl=http://identity-svc
    ports:
      - 5073:80
    depends_on:
      - postgres
      - rabbitmq
volumes:
  pgdata:
  mongodb_data:
