import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ReactNode } from "react";
import { Toaster } from "sonner";
import { toastOptions } from "../lib/utils";
import Navbar from "./_nav/navbar";
import "./globals.css";
import SignalrProvider from "./providers/signalrProvider";
import { getCurrentUser } from "./_actions/auth-actions";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Carties",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: ReactNode }) {
  const user = await getCurrentUser();
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <main className="container mx-auto px-5 pt-10">
          <SignalrProvider user={user}>{children}</SignalrProvider>
        </main>
        <Toaster theme="system" richColors invert closeButton duration={3000} toastOptions={toastOptions} />
      </body>
    </html>
  );
}
